### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by dtedwards** [Biketrail-Awesome-Sauce/MNBikeways#1]
Currently getting an Error 500 on the Tile call in index.html

**Comment by hillx075** [comment]
Hmmmm. I made a new one. Can I email it to you?

**Comment by dtedwards** [comment]
Did you see the changes I made to what you sent me? I don't *Think* my changes are causing the issue.

dtedwards86@gmail.com

**Comment by dtedwards** [comment]
We're going to ignore this issue for as long as we can for this prototyping project

**Comment by hillx075** [comment]
Looks great.

You get some hillshade when using the natgeo baselayer.

It's pretty fast and added my location no problem this morning!

Good luck y'all.
-d.hill
